### ISSUE TITLE
DPO Training error:   NameError: name 'RetroConfig' is not defined 

### ISSUE THREAD

**Issue by sunilitggu** [NVIDIA/NeMo-Aligner#262]
Following the steps provided for DPO Training at https://docs.nvidia.com/nemo-framework/user-guide/latest/modelalignment/dpo.html

` Starting training
*******STARTING********
---------------
Starting training
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
Traceback (most recent call last):
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
NameError: name 'RetroConfig' is not defined
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
NameError: name 'RetroConfig' is not defined
NameError: name 'RetroConfig' is not defined
NameError: name 'RetroConfig' is not defined
NameError: name 'RetroConfig' is not defined
NameError: name 'RetroConfig' is not defined
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
NameError: name 'RetroConfig' is not defined
Traceback (most recent call last):
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/examples/nlp/gpt/train_gpt_dpo.py", line 22, in <module>
    from nemo_aligner.algorithms.dpo import DPOTrainer, dpo_custom_collate
  File "/vast/core42-nlp/users/sunil.sahu/projects/llm/dpo_training/NeMo-Aligner/nemo_aligner/algorithms/dpo.py", line 22, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.megatron_batch_samplers import (
  File "/opt/NeMo/nemo/collections/nlp/__init__.py", line 15, in <module>
    from nemo.collections.nlp import data, losses, models, modules
  File "/opt/NeMo/nemo/collections/nlp/models/__init__.py", line 28, in <module>
    from nemo.collections.nlp.models.language_modeling import MegatronGPTPromptLearningModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/__init__.py", line 20, in <module>
    from nemo.collections.nlp.models.language_modeling.megatron_retro_model import MegatronRetroModel
  File "/opt/NeMo/nemo/collections/nlp/models/language_modeling/megatron_retro_model.py", line 37, in <module>
    from nemo.collections.nlp.data.language_modeling.megatron.retro_dataset import build_train_valid_test_datasets
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 55, in <module>
    class RETRODataset(Dataset):
  File "/opt/NeMo/nemo/collections/nlp/data/language_modeling/megatron/retro_dataset.py", line 56, in RETRODataset
    def __init__(self, cfg, retro_config: RetroConfig, tokenizer, mcore_retro_dataset, number_samples_with_neighbors):
NameError: name 'RetroConfig' is not defined
`

**Comment by sunilitggu** [comment]
NA
